language: ruby

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

services:
  - docker

install: gem install html-proofer

script: "htmlproofer --only-4xx --typhoeus-config '{\"headers\": {\"User-agent\": \"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0\"}}' index.html"

before_deploy: docker run --rm -u $(id -u):$(id -g) -v $(pwd):/home astefanutti/decktape /home/index.html /home/Code_versioning_an_introduction_with_Git.pdf

deploy:
  provider: releases
  api_key:
    secure: "HfYnWf5ngB4ei0ig1xj8AGF7zfS27cjJ+3Hj+stIYwBn4vAZjGRTHUeUdNpNzmG1CLjQmtAV2EMtyiim5EOQUmx3YIdqgmqHMiycb8e9zFvlUDzl9kmMSekGYOc1Hcq0juJhZhjpTJUZivMaiHyNY2Pf4ZIq8AVBh58a88rLrEaRfbj3RlciO9AiseZWx1ptQ/oVUVYUIvFW3bNQKNw+4bkMcD5VC7xcgaX6O4HdkKZVo/N0we1r29MA1iSY3SDLARsgnwHbR2DTJQ1HsBsDikpX7f9GFn9h927Ojb2bT4VrRpns6OeZQreHK/mxpBsjDpDjb+1GQDX+OzFynSCbof2DOFEXbjZMfhxLIhnMFcEedpsPMgDGtdQTur4dqX/LllsV5w66Ek7Q5AscPnatefgVufCjouE+NF6AugcfEAwrB8D46xs9zeIHGGzcxmiubKYoX/jC7riJHbqbvNOaOMJwhxW0MKGyMZ6/KXf2KCSlQrQI2qwkIr+D+RIuiqvGbg9Mj/vE2ryZotfz4S4Payb46QuDawwBjzqvb9VzpCRpwzGn+mOdokJ2xf9UpenVKLD6iLiXJsMi5TAevoAH+YJPFO9adipxz3iNc0pAEeqUGd0EB02fU5+XYBEslG2WmYzWdDphn/wdNcKS9ZDXFDOTe8MeWmT+CXEQStsuq58="
  file: Code_versioning_an_introduction_with_Git.pdf
  cleanup: false
  skip_cleanup: true
  overwrite: true
  on:
    repo: SkypLabs/git-slideshow
    tags: true

notifications:
  email:
    on_success: never
